### ISSUE TITLE
leaflet plugin

### ISSUE THREAD

**Issue by jayenashar** [skedgo/tripgo-api#11]
Mauro, Can you nominate someone in the BB team to make a leaflet (http://leafletjs.com/ ) plugin?  We can probably make js libraries from the swagger, but we'll need a thin wrapper for leaflet.  Thanks.

**Comment by MauroGomez** [comment]
Do you mean a plugin for swagger? for MkDocs? What should the plugin do?

**Comment by jayenashar** [comment]
we want to make something that can be listed on this page: http://leafletjs.com/plugins.html

some ideas:

- Search & popups - use geocode.json to search stop names and codes, maybe w3w
- Routing - routing.json (waypoint & skedgoify too maybe)
- 3rd party integration - open maps in tripgo

**Comment by MauroGomez** [comment]
Ok, I understand.  I've already done a quick look at Leaflet and existing plugins, don't seem to be too hard depending on what we want to do: using geocoding.json to search stop names and codes seem to be easier than display trips from A to B by hitting routing.json.

Just two questions for now, to have a little more context:
- which is the underlying motivation? Marketing? a particular application / use case we have in mind?
- is there a particular deadline and/or priority for this task?

Not sure who to nominate yet, probably me :).

**Comment by jayenashar** [comment]
Yes, marketing is the underlying motivation.  (Can I say that in a public issue?  @nighthawk )  I think this would be the best way to bring in API users.

@sandraskedgo is probably best to ask about a deadline/priority, since she is the managing the marketing of the API.

**Comment by MauroGomez** [comment]
**Leafleat plugin proposal:**

Add TripGo routing capabilities to leafleat map by providing:

1. basic API to: 
    - easily hit our routing.json endpoint.
    - draw trips on map as they come from routing.json.
    - giving more control to client for a customized implementation.

2. pre-built features, implemented on top of 1, to: 
   - pick from and to by dropping pins on map, automatically triggering routing when both from and to were defined. 
   - display trips on map and switch between them with very basic selector (e.g. prev-next controls).
allowing minor customizations, as control position.

About hitting routing.json, plugin can probably use open-data key by default, allowing to specify paid key for more quota. Some listed plugins do that, e.g.: https://github.com/route360/r360-js#api-key

**Some benefits:**
- Promote our routing API.
- TripGo web-app as client: can use this new plugin as an alternative to current map drawing features based on google maps.

**Similar plugin:**
http://www.liedman.net/leaflet-routing-machine/

**Comment by jayenashar** [comment]
it looks like you are more familiar with leaflet than i.  will the new plugin draw trips on any map layer, or only google maps?  a lot of leaflet users use mapbox.  if you can draw them on google maps, then finderful.com may use this.  finderful.com will be drawing about 20 trips simultaneously though, so would need to customize the line style quite a bit (e.g., the line transitions from color A to color B based on travel minutes, not pixels).

it looks like LRM doesn't do routing itself, but rather uses plugins.  maybe for a first pass, we write a plugin that works with LRM?

**Comment by MauroGomez** [comment]
Changing map layers means just change tiles, so our plugin should work with any layer, probably we can let the plugin client decide?

Yes, I suppose writing a routing plugin to use as input to LRM should be easier than implement a plugin from scratch. Will this fit our purpose? We will gain just to appear as one more routing engine for LRM, provided we get listed by them. Also LRM doesn’t seem to contemplate alternative trips, so not very compatible with our multi-mode / multi-results capabilities.

Or should we face the complete plugin that will put us in the leaflet list?

@gimenna is already playing with Leaflet, she draw segments from encoded waypoints, and plans to continue with custom markers (custom widgets as markers).

**Comment by gimenna** [comment]
I've been working with Leaflet. As a first approach,  I have an web application that routes (hitting our backend) from a point to another selected by the user clicking on the map, and show all options for a trip.
Next you can see some screenshots, keep in mind that it's only a first approach.

<img width="1680" alt="leaflet_test1" src="https://user-images.githubusercontent.com/8352348/33223009-9f5138dc-d13a-11e7-92a3-17a440701a08.png">
<img width="1674" alt="leaflet_test2" src="https://user-images.githubusercontent.com/8352348/33223048-13577098-d13b-11e7-9a4a-fc97d635554f.png">

As @MauroGomez said I'll continue with custom markers.

**Comment by jayenashar** [comment]
this is fantastic!  is it something you can release today, so we can start getting feedback from real users?  custom markers are nice, but do we know if users care?  @nighthawk did someone request this?

**Comment by gimenna** [comment]
> is it something you can release today, so we can start getting feedback from real users?

I don't think so, it's a really beta version.

**Comment by gimenna** [comment]
As you know, I've been working on plugin. I'm using TripGo icons and I've added them as plugin's resources. 
Is it ok or Do you want to use different ones?

Here you can see a screenshot:

![image](https://user-images.githubusercontent.com/8352348/34106512-4300c548-e3d7-11e7-8dd4-72ee67fd02f2.png)

**Comment by jayenashar** [comment]
lgtm.  what is left for it to be released?  can you work with @duduct and @sandraskedgo to set up a demo page on skedgo.com ?

**Comment by gimenna** [comment]
I'm testing, fixing bugs and adding documentation.  
https://github.com/skedgo/leafletPlugin

**Comment by nighthawk** [comment]
> As you know, I've been working on plugin. I'm using TripGo icons and I've added them as plugin's resources.

Fine to use those as the iOS and Android equivalents are also in our open source repositories.

**Comment by gimenna** [comment]
@jayen, we have plublished git repository:  https://github.com/skedgo/leaflet.tripgo.routing
Here you can find a plugin demo:
 > https://skedgo.github.io/leaflet.tripgo.routing/

We have published it in npm too:
 > https://www.npmjs.com/package/leaflet.tripgo.routing

I've created an account for skedgo in npm using my email. Tell me if you want me to set another email for this account.

**Comment by jayenashar** [comment]
fantastic.  i notice my cursor changes when i hover over a trip, but when i click on the trip nothing happens.  not sure if the cursor-change is the error or the nothing-on-click.  using firefox.

now how do we get listed by LRM and/or leaflet?

can we get this added to https://developer.tripgo.com/ ?  at least a link if not a copy of the docs?  @MarianoTucat 

can you switch npm to use the api email?  @gimenna should i add you to that mailing list?

**Comment by gimenna** [comment]
> fantastic. i notice my cursor changes when i hover over a trip, but when i click on the trip nothing happens. not sure if the cursor-change is the error or the nothing-on-click. using firefox.

no, it's not an error, I've copied tripGo's styles. Would you like me to remove this behavior.

>   now how do we get listed by LRM and/or leaflet?

 Now I know that it's ok for you. I'm going to do a fork of leaflet project and a pull request to them with the plugin list update.

**Comment by gimenna** [comment]
@nighthawk @jayenashar Leaflet has just approved our pull request, we are in leaflet's plugin list now!!
http://leafletjs.com/plugins.html#routing

**Comment by MarianoTucat** [comment]
> can we get this added to https://developer.tripgo.com/ ? at least a link if not a copy of the docs? 

Just added it to the docs as a link to the repo and the demo

**Comment by nighthawk** [comment]
Great stuff! Can you also write up a little getting started guide for this - how to embed it in a website? Could also have a little section on the difference of the leaflet plugin compared to the web widget for leaflet noobs like myself.

**Comment by jayenashar** [comment]
> no, it's not an error, I've copied tripGo's styles. Would you like me to remove this behavior.

yes, please make the hover not special.

**Comment by gimenna** [comment]
hover special has been removed.

**Comment by gimenna** [comment]
> how to embed it in a website? 

Readme doc has info about how to embed it in a website. Do you want me to add something else?

**Comment by nighthawk** [comment]
I asked before I checked. Looks all good to me!

**Comment by gimenna** [comment]
> can you switch npm to use the api email?

@jayenashar npm email updated to api@tripgo.com!
