### ISSUE TITLE
"mini" is missing from documentation

### ISSUE THREAD

**Issue by pnuts2** [skedgo/tripgo-api#117]
There's a field `mini` in the `SegmentTemplate` JSON, but I can't see this documented on our API page under "segmentTemplates". Was I looking at the wrong place?

```
▿ Optional<Any>
  ▿ some : 3 elements
    ▿ 0 : 2 elements
      - key : instruction
      - value : Ride Bicycle
    ▿ 1 : 2 elements
      - key : mainValue
      - value : 9 miles
    ▿ 2 : 2 elements
      - key : description
      - value : Mascot Station
```

**Comment by pnuts2** [comment]
alright. Should we nonetheless include this in the doc and mark it as deprecated in version x? Or just not return that to avoid confusion? @MarianoTucat your call to action and close this issue.

**Comment by nighthawk** [comment]
We shouldn’t remove things without bumping the version. I don’t think we should document it any more than “this exists for backwards compatibility and is deprecated”, no need to give details what is in it.
