### ISSUE TITLE
has `realTimeStatus`been deprecated?

### ISSUE THREAD

**Issue by pnuts2** [skedgo/tripgo-api#122]
Our client is still looking for `realTimeStatus` field in `segment` JSON. But this field isn't documented nor returned. iOS client is using this to update `service`. Expected values include

- `IS_REALTIME`
- `CAPABLE`
- `CANCELLED`

I also noted that we have `realTime` and `isCancelled` fields. Has `realTimeStatus` been deprecated then?

**Comment by gimenna** [comment]
[PR#126](https://github.com/skedgo/tripgo-api/pull/126)
