### ISSUE TITLE
Detailed cost components per segment

### ISSUE THREAD

**Issue by nighthawk** [skedgo/tripgo-api#125]
From #77:

> We can additionally also add a `costComponents` list which breaks down the cost in a structured way. For public transport that could then have a single element with the ticket name and the ticket cost. For driving it could have a multiple elements for fuel, toll, and the additional wear & tear that we include. (Nice side benefit of it being self-documenting where the JSON then directly answers the questions of "what's included in your driving cost?")

**Comment by MarianoTucat** [comment]
this is resolved
