### ISSUE TITLE
Document "bestOnly" parameter for routing

### ISSUE THREAD

**Issue by nighthawk** [skedgo/tripgo-api#136]
Related inquiry whether there's a way to only get the fastest result from a routing query, answered below.

---

1. Provide "bestOnly=true" as an additional parameter to routing.json
2. Use a weight like "wp=(0.1,0.1,2.0,0.1)" to prefer faster results

There's no guarantee it'll return the fastest, as even with strong bias for time over other factors (like price) you might still get as the best result a trip that's slower but saves you a lot of money (e.g., taking a cheap commuter train for 3 stops versus a fast but expensive intercity train for 1 stop).

**Comment by gimenna** [comment]
Done [PR](https://github.com/skedgo/tripgo-api/pull/137)
