### ISSUE TITLE
Fixed and region-independent base URL for all endpoints

### ISSUE THREAD

**Issue by nighthawk** [skedgo/tripgo-api#2]
Makes using the API easier and avoids potential problems when hard-coding endpoints but those regions then moving to different servers.

We might still want to keep the list of region-dependent URLs in `regions.json` to allow client-side failover.

**Comment by nighthawk** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Single api.tripgo.com hostname](https://trello.com/c/2bFwiKFY/1-single-api-tripgo-com-hostname)

**Comment by MarianoTucat** [comment]
this is done
