### ISSUE TITLE
[Booking Beta] /booking, indicating default parameter values

### ISSUE THREAD

**Issue by pnuts2** [skedgo/tripgo-api#20]
Can we do something similar to "validOnly" that indicating first=1 and max=7 are the default value if none were provided?

**Comment by MarianoTucat** [comment]
I don't understand, the default values are already there. How do you see them? How do you want them to be shown?

**Comment by pnuts2** [comment]
What I meant was the numbers 1 and 7 were not immediately obvious to me are default values, especially when validOnly has `false (default)`, i.e., has default next to it. The way I interpret it would be 1 and 7 are the values there for me to "Try it out!". I'd never know by looking at those two values that if I simply call the /booking without any parameters, I'd be getting first=1 and max=7. But it's obviously to me if I didn't specify validOnly, I will be getting everything.

**Comment by MarianoTucat** [comment]
@pnuts2 I think the new tool to visualize the data solves the issue, see [here](https://skedgo.github.io/tripgo-api/#tag/Booking-Beta), if you agree, can you close this issue?
