### ISSUE TITLE
Adding account APIs

### ISSUE THREAD

**Issue by pnuts2** [skedgo/tripgo-api#21]
To proceed with TripGo wallet, I'm currently querying the following APIs

- api/user
- account/alias

Can we please have these APIs documented? 

Also, is it possible that all account APIs have the same entry point, perhaps api/user & apu/user/alias? Just finding it weird to have two completely different URLs to fetch (more or less) the same thing, e.g., info about a user.

**Comment by pnuts2** [comment]
Had a look, can we move the contents of account/alias to api/user?

api/user currently returns just a single email address, perhaps we could replace this with an array of aliases like this?

`
"aliases": [
    {
      "email": "brian@skedgo.com",
      "validated": true,
      "primary": true
    }
  ]
`

**Comment by MarianoTucat** [comment]
Closing this one since this is already addressed.
