### ISSUE TITLE
The usage of "User-Agent" header in "/auth/{region}"

### ISSUE THREAD

**Issue by thuutin** [skedgo/tripgo-api#23]
- What's the role of "User-Agent" header in a scope of all backend APIs?
I found that modifying the "User-Agent" header changes the "CompanyInfo.website" property in this API [Auth API](http://skedgo.github.io/tripgo-api/swagger/#!/Auth/resource_AuthServiceImpl_getModesForRegion_GET)

- Is using "User-agent" header a good way to send app name/version?

**Comment by MarianoTucat** [comment]
That shouldn't be affecting the results, @thuutin can you provide and example so I can reproduce the issue?

**Comment by thuytrinh** [comment]
@MarianoTucat https://github.com/skedgo/tripgo-android/issues/1770

**Comment by MarianoTucat** [comment]
oh, yes, that's true, the about website does depend on the user-agent, that is what @nighthawk requested, or at least, what I understood.

**Comment by MarianoTucat** [comment]
FYI, iOS uses the following userAgent:

`TripGo/9469 CFNetwork/808.3 Darwin/16.3.0`

**Comment by MarianoTucat** [comment]
And I'm using the first string before `/` as `productName` and the remainder until the first space as  `productVersion`

**Comment by thuutin** [comment]
@MarianoTucat thanks.
@nighthawk Are you using `TripGo/9469 CFNetwork/808.3 Darwin/16.3.0` as userAgent for every request ?

**Comment by nighthawk** [comment]
I think that's just the default of what iOS does.
