### ISSUE TITLE
[Account API] - Balance & transactions

### ISSUE THREAD

**Issue by pnuts2** [skedgo/tripgo-api#26]
There are currently quite a few API endpoints that we have to work with when working on account & wallet. Specifically,

`api/user`
`account/alias`
`wallet/transactions`

Any chance these can be consolidated somehow? Something like

`api/user`
`api/user/wallet/transactions`

while moving alias as part of the JSON returned by `api/user`, since that is already returning a list of phone numbers I have. I don't see how email is any different?

Not sure if `user/wallet/` is a good approach. I"ll leave that to @MarianoTucat to decide. A couple things I'd like to suggest

with `api/user`, let's return balance and the latest 10 transactions. Then, with `wallet/transactions`, in addition to returning a list of transactions, let's also include "balance" field, i.e., {"balance" : 890, "result" : []}. That way, I can update the entire wallet view with one API call.

**Comment by MarianoTucat** [comment]
Closing this one since this is already addressed.
