### ISSUE TITLE
Format of `from` and `to` of routing.json

### ISSUE THREAD

**Issue by thuytrinh** [skedgo/tripgo-api#27]
What's the correct format of `from` and `to` params of `routing.json` endpoint? In https://skedgo.github.io/tripgo-api/#tag/Routing, it indicates `(lat,lng)` but [this fix](https://github.com/skedgo/tripkit-android/pull/157) suggested `(lat,lng)"address"`.

**Comment by MarianoTucat** [comment]
I need to update the format, it formerly was `(lat,lng)` but we extended it to include the address like `(lat,lng)"address"` in order to avoid a new reverse geocoding of the address and to reuse the exact same address the user is seeing to external services, like Uber.

**Comment by thuytrinh** [comment]
Thanks! I'll let you close this after bringing https://skedgo.github.io/tripgo-api/#tag/Routing up to date.

**Comment by nighthawk** [comment]
Thanks, Thuy. I've just fixed this.
