### ISSUE TITLE
Unexpected decoded Polylines

### ISSUE THREAD

**Issue by Maxwell2022** [skedgo/tripgo-api#31]
Hey guys, I was just trying out your API to see what is capable of. I've tried a very simple routing request: 

```
curl --request GET \
  --url 'https://darkages-au-nsw-sydney-tripgo.skedgo.com/satapp/routing.json?v=11&from=-33.884738%2C151.209664&to=-33.905058%2C%20151.211071&modes=wa_wal' \
  --header 'cache-control: no-cache' \
  --header 'postman-token: f8579c90-5d1c-0579-0829-40dc65c81b88' \
  --header 'x-tripgo-key: xxxxxxxxxxxxxxxxxxxxxx'
```

This is working fine. Then comes the `encodedWaypoints`:

![image](https://cloud.githubusercontent.com/assets/670701/24599140/2e0935e6-1892-11e7-9c61-5f37f8f7578e.png)

```
"streets": [
        {
          "encodedWaypoints": "rbymEkc|y[]dB??xAEH@PChACvBG@?`@@^P`Ah@??g@dBNZ??p@Jl@?|ALF@|@DbDPzBNdBHhAJvD^?@`@BT@@?bAHxBVlAPAFz@@L@Z@F?z@J??pDb@rDb@??fBRXNG@dAHtAN`BN`AHzBLT?X?v@AfA@vBTVBbALPBjAP?@xAVzB^F@HBD@dANbAPPBDD??EEEYRqC@QHkA?@FY^c@HM??D_@\\}@?@A?N_@LyALi@HMLaA@I@GDIFYRw@FGASn@?FB?A????dAwDBGPHj@aCv@Ps@]??r@\\"
        }
      ],
```

Using [Google Polyline Utility](https://developers.google.com/maps/documentation/utilities/polylineutility) to decode this:

![image](https://cloud.githubusercontent.com/assets/670701/24599271/b09b9cb0-1892-11e7-9d68-778257e06747.png)

Here is what Google is recommending:

![image](https://cloud.githubusercontent.com/assets/670701/24599307/e8a077c0-1892-11e7-84e7-39ce2f14c37b.png)

As you can see the end of the trip return by trip go is incorrect, here he is zooming in:

![image](https://cloud.githubusercontent.com/assets/670701/24599331/1119233c-1893-11e7-908c-80765d55cd1b.png)

Not sure if it's coming for the API and the way it's been encoded or if it's coming for the google polyline utility or maybe just and encoding issue in my test...

**Comment by jayenashar** [comment]
Hi Max, the usual issue is that Google's encoding allows backslashes, and that backslashes in JSON strings are escaped with a second backslash, so if you are copying and pasting, you need to substitute the double-backslashes for single backslashes.

**Comment by jayenashar** [comment]
Tried it myself and it looks ok to me with
```
rbymEkc|y[]dB??xAEH@PChACvBG@?`@@^P`Ah@??g@dBNZ??p@Jl@?|ALF@|@DbDPzBNdBHhAJvD^?@`@BT@@?bAHxBVlAPAFz@@L@Z@F?z@J??pDb@rDb@??fBRXNG@dAHtAN`BN`AHzBLT?X?v@AfA@vBTVBbALPBjAP?@xAVzB^F@HBD@dANbAPPBDD??EEEYRqC@QHkA?@FY^c@HM??D_@\}@?@A?N_@LyALi@HMLaA@I@GDIFYRw@FGASn@?FB?A????dAwDBGPHj@aCv@Ps@]??r@\
```
![image](https://cloud.githubusercontent.com/assets/1137152/24599681/a4bacb30-1894-11e7-9f77-cc9f7266f62f.png)
