### ISSUE TITLE
Differences between URLs

### ISSUE THREAD

**Issue by pnuts2** [skedgo/tripgo-api#43]
So what is the difference between the following URLs

- temporaryURL
- saveURL
- shareURL
- updateURL
- plannedURL

Can we attach some descriptions to them, please?

**Comment by jayenashar** [comment]
saveURL - i thought this was to get a shareURL
shareURL - permanent URL (for a trip)
updateURL - to get updates (for a trip)
plannedURL - to report what trip the user is planning to take

**Comment by pnuts2** [comment]
Can we tell developers when to use what? Or even can we provide a user case where each of these URLs is used, e.g., you need to get `saveURL` in order to get `shareURL`. 

By looking at the documentation along, I don't know when to use which?

**Comment by nighthawk** [comment]
Yes, if there's no `saveURL`, you can use the `shareURL` to get a `shareURL`.

**Comment by nighthawk** [comment]
`temporaryURL` is a URL to download the trip again, but it'll stop working within a few minutes. It's not long-lived and shouldn't be used for sharing (for that you use the `shareURL`), but it can be used for [Apple's Handoff](https://support.apple.com/en-us/HT204681) or for sending a trip from an app extension back to the main app.

**Comment by nighthawk** [comment]
Got another question about this, just pasting my answer here:

- `temporaryURL` is a way to retrieve a recently computed trip again – if you open it in the browser, it will show the trip in our web app, but you the typical use case of this is to send an “accept: application/json” header to get the trip in JSON format again. The primary use-case for this is when you say want to send the trip from one device to another, when the user is transitioning say from the phone app to viewing to continuing the trip in an in-car system. Those URLs can only be used shortly aftter computing the trip in the first place.

- `saveURL` is used when the trip should stick around for longer. You hit this URL and then get back a persistent URL for the trip. This can be used to share the trip with other people, or to save it to your calendar. That URL then also either shows the trip in our web app, or in JSON format, depending on the request. If a trip was previously saved the JSON will have a `shareURL` with that URL in it.

- `updateURL` updates a recently computed trip with real-time data. In the longevity it’s similar to temporaryURL, but it only makes sense for trips happening now anyway. Note that this is only present if we have real-time data for the trip.

- `plannedURL` is used to report back to the backend which trip a user intends to take or is currently taking. The trip then gets added to an internal anonymised database, which we use in for analytics to infer general usage patterns. It is a short-cut that avoids having to send detailed information about the trip (as our backend already has the details of the trip). It is entirely optional for you to use – if you do, we should have a chat, as we can then provide a dedicated database for you, in case you want to analyse this kind of usage data.

**Comment by MarianoTucat** [comment]
just added Adrian's answer to the descriptions of the fields
