### ISSUE TITLE
sources field in both groups & segmentTemplates

### ISSUE THREAD

**Issue by pnuts2** [skedgo/tripgo-api#45]
As titled. The descriptions for both are identical: when they are present, they should get displayed on the relevant screen/views.

So what's the difference between the two?

**Comment by nighthawk** [comment]
The one in segment templates has the sources just for that segment, while the one in the trip groups is the union. It's up to the client to decide which to use. The latter is there for convenience.

**Comment by MarianoTucat** [comment]
added specific description messages to each field
