### ISSUE TITLE
locations.json response

### ISSUE THREAD

**Issue by pnuts2** [skedgo/tripgo-api#48]
Our API doc has the followings,

![screen shot 2017-09-18 at 2 58 33 pm](https://user-images.githubusercontent.com/2722800/30529541-c937b420-9c81-11e7-81ed-440ac1fcb23b.png)

An example of actual response is this,

<pre>
{
                    "class": "StopLocation",
                    "code": "AU_NSW_Sydney-200020",
                    "lat": -33.8613,
                    "lng": 151.2103,
                    "modeInfo": {
                        "alt": "train",
                        "identifier": "pt_pub_train",
                        "localIcon": "train"
                    },
                    "name": "Circular Quay Station",
                    "popularity": 15645,
                    "stopCode": "AU_NSW_Sydney-200020",
                    "stopType": "train"
},
</pre>

- Our doc says `timezone` is required, but actual response is missing such.
- Our doc says missing `wheelchairAccessible` means unknown. But Circular Quay Station should be accessible even with static data?
- Our doc does not have `stopCode` but actual response does. What's the difference between `code` and `stopCode`.

**Comment by nighthawk** [comment]
> Our doc says timezone is required, but actual response is missing such.

Good point. Will need to make sure we add that on the backend.

> Our doc says missing wheelchairAccessible means unknown. But Circular Quay Station should be accessible even with static data?

This information might not be available on the "parent station" level like here with Circular Quay and just on the per-platform level.

> Our doc does not have stopCode but actual response does. What's the difference between code and stopCode.

No difference. It's there for backwards compatibility and might get removed. Not included in docs on purpose.

**Comment by MarianoTucat** [comment]
Closing this one since this is already addressed.
