### ISSUE TITLE
skedgoify: no result

### ISSUE THREAD

**Issue by jayenashar** [skedgo/tripgo-api#50]
works fine for other homes, but not this one.  works fine for pt_pub but not me_car.

`{"config":{"v":11},"modes":["me_car"],"frame":{"startTime":1507467600,"endTime":1508072400},"vehicles":[{"type":"car","garage":{"lat":-33.7682461,"lng":150.7892457}},{"type":"bicycle","garage":{"lat":-33.7682461,"lng":150.7892457}}],"items":[{"class":"event","id":"home","startTime":1507467600,"endTime":1508072400,"location":{"lat":-33.7682461,"lng":150.7892457},"priority":0},{"class":"event","id":"work","startTime":1507500000,"endTime":1507528800,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1507586400,"endTime":1507615200,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1507672800,"endTime":1507701600,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1507759200,"endTime":1507788000,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1507845600,"endTime":1507874400,"location":{"lat":-33.877307,"lng":151.205902},"priority":2}]}`

**Comment by MarianoTucat** [comment]
Created internal ticket to track this.
