### ISSUE TITLE
skedgoify: me_car results don't fill in query information

### ISSUE THREAD

**Issue by jayenashar** [skedgo/tripgo-api#52]
query info isn't properly filled:

pt_pub first trip result:

```
queryIsLeaveAfter:false
queryTime:1507500000
```

me_car first trip result:

```
queryIsLeaveAfter:true
queryTime:0
```

queries are the same except the `modes` parameter

**Comment by drtimcooper** [comment]
I can't reproduce this (except with RoughRouter results).  I've added this assert:

        // Put it in the exact cache:
        pair = new QueryResultPair(query);
        pair.trips = trips;
        for (Trip trip : trips)
            assert(trip.queryTime != 0);//$$$
        exactCache.put(query, pair);

It doesn't fire on SkedgoifyTests#test3382().  Maybe I don't know how to use github.  Is there some context?  Where can I get the input.json?

**Comment by jayenashar** [comment]
I'll set up a test for you later.  Possibly this is related to the JSON conversion and tripOutputFormat as #53 is.

**Comment by jayenashar** [comment]
fixed.  will be pushed out soon for your/my testing.

**Comment by jayenashar** [comment]
:( looks like walk & cycle ignore the date now.  they seem to set the query time to the right time but the first date.

**Comment by nighthawk** [comment]
@jayenashar , this has since been fixed and deployed.

(Internal ticket number is 8860.)
