### ISSUE TITLE
skedgoify: not getting any results for cy_bic

### ISSUE THREAD

**Issue by jayenashar** [skedgo/tripgo-api#54]

**Comment by nighthawk** [comment]
@jayenashar, do you have a sample input?

**Comment by jayenashar** [comment]
`{"config":{"v":11},"modes":["cy_bic"],"frame":{"startTime":1507467600,"endTime":1508072400},"vehicles":[{"type":"car","garage":{"lat":-33.102664947509766,"lng":151.54347229003906}},{"type":"bicycle","garage":{"lat":-33.102664947509766,"lng":151.54347229003906}}],"items":[{"class":"event","id":"home","startTime":1507467600,"endTime":1508072400,"location":{"lat":-33.102664947509766,"lng":151.54347229003906},"priority":0},{"class":"event","id":"work","startTime":1507500000,"endTime":1507528800,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1507586400,"endTime":1507615200,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1507672800,"endTime":1507701600,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1507759200,"endTime":1507788000,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1507845600,"endTime":1507874400,"location":{"lat":-33.877307,"lng":151.205902},"priority":2}]}`

**Comment by jayenashar** [comment]
working now
