### ISSUE TITLE
skedgoify: ignores daily travel cap

### ISSUE THREAD

**Issue by jayenashar** [skedgo/tripgo-api#57]
opal has a daily travel cap of $15.40, but skedgoify tells me it's $10.08 each way.

`{"config":{"v":11},"modes":["pt_pub"],"frame":{"startTime":1508072400,"endTime":1508677200},"vehicles":[{"type":"car","garage":{"lat":-33.102664947509766,"lng":151.54347229003906}},{"type":"bicycle","garage":{"lat":-33.102664947509766,"lng":151.54347229003906}}],"items":[{"class":"event","id":"home","startTime":1508072400,"endTime":1508677200,"location":{"lat":-33.102664947509766,"lng":151.54347229003906},"priority":0},{"class":"event","id":"work","startTime":1508104800,"endTime":1508133600,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1508191200,"endTime":1508220000,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1508277600,"endTime":1508306400,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1508364000,"endTime":1508392800,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1508450400,"endTime":1508479200,"location":{"lat":-33.877307,"lng":151.205902},"priority":2}]}`

**Comment by MarianoTucat** [comment]
created internal ticket
