### ISSUE TITLE
Does the server return `wheelchairAccessible` property of Segments, if I route with wheelchair=false? 

### ISSUE THREAD

**Issue by thuutin** [skedgo/tripgo-api#58]
I am seeing `wheelchairAccessible` is returned regardless of the routing parameter `wheelchair=false`. Is this intended? @MarianoTucat @thuytrinh @nighthawk

**Comment by thuutin** [comment]
@thuytrinh Can you label this issue as `question`?

**Comment by nighthawk** [comment]
@JulietaMarcos, question for you

**Comment by JulietaMarcos** [comment]
@thuutin: yes, for public transport the `wheelchairAccessible` property is always returned (unless unknown), regardless of the `wheelchair` routing parameter.

**Comment by thuutin** [comment]
Thanks
