### ISSUE TITLE
skedgoify: no mixed trips

### ISSUE THREAD

**Issue by jayenashar** [skedgo/tripgo-api#59]
i haven't seen any mixed trips for any input yet.  i expect one for this input

`{"config":{"v":5},"modes":["pt_pub","me_car"],"frame":{"startTime":1508072400,"endTime":1508677200},"vehicles":[{"type":"car","garage":{"lat":-35.18030548095703,"lng":150.572998046875}},{"type":"bicycle","garage":{"lat":-35.18030548095703,"lng":150.572998046875}}],"items":[{"class":"event","id":"home","startTime":1508072400,"endTime":1508677200,"location":{"lat":-35.18030548095703,"lng":150.572998046875},"priority":0},{"class":"event","id":"work","startTime":1508104800,"endTime":1508133600,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1508191200,"endTime":1508220000,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1508277600,"endTime":1508306400,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1508364000,"endTime":1508392800,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1508450400,"endTime":1508479200,"location":{"lat":-33.877307,"lng":151.205902},"priority":2}]}`

https://tripgo.com/trip/01b80ebd-9f5e-4cfe-9dc2-a9e436233887 shows the mixed trip has a higher rank, but this query tells me to just stay home.  should at least tell me to drive like `"modes":["me_car"]` does.

**Comment by MarianoTucat** [comment]
created internal ticket
