### ISSUE TITLE
mixed trip only once?

### ISSUE THREAD

**Issue by jayenashar** [skedgo/tripgo-api#60]
`{"config":{"v":5},"modes":["pt_pub","me_car"],"frame":{"startTime":1508072400,"endTime":1508677200},"vehicles":[{"type":"car","garage":{"lat":-33.88322448730469,"lng":151.13038635253906}},{"type":"bicycle","garage":{"lat":-33.88322448730469,"lng":151.13038635253906}}],"items":[{"class":"event","id":"home","startTime":1508072400,"endTime":1508677200,"location":{"lat":-33.88322448730469,"lng":151.13038635253906},"priority":0},{"class":"event","id":"work","startTime":1508097600,"endTime":1508126400,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1508184000,"endTime":1508212800,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1508270400,"endTime":1508299200,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1508356800,"endTime":1508385600,"location":{"lat":-33.877307,"lng":151.205902},"priority":2},{"class":"event","id":"work","startTime":1508443200,"endTime":1508472000,"location":{"lat":-33.877307,"lng":151.205902},"priority":2}]}`

contrary to #59 i did find a mixed-trip result.  this one has two oddities:

* only take the mixed-trip one day of the week
* only take four trips to/from work

**Comment by MarianoTucat** [comment]
created internal ticket
