### ISSUE TITLE
Bookings in TripKit Android (documentation)

### ISSUE THREAD

**Issue by jayenashar** [skedgo/tripgo-api#63]
bottom of https://github.com/skedgo/tripgo-api/blob/gh-pages/docs/enterprise/bookings-api.md

low priority

**Comment by thuytrinh** [comment]
@jayenashar Emmanuel knows this better than me. You can create a Redmine and assign him.

**Comment by jayenashar** [comment]
@nighthawk can we add @elagarrigue to this repo?
