### ISSUE TITLE
Cost of this segment in local currency

### ISSUE THREAD

**Issue by jayenashar** [skedgo/tripgo-api#77]
I'm not seeing the `SegmentTemplate.cost` field being filled as per https://developer.tripgo.com/specs/#tag/Routing%2Fpaths%2F~1routing.json%2Fget .

slack conversation: https://tripgoapi.slack.com/messages/C142FGB2R/convo/C142FGB2R-1516925519.000173/

example query:

https://granduni-au-nsw-sydney-tripgo.skedgo.com/satapp/routing.json?from=(-33.90925670000001,151.1044405)&to=(-33.86390160000001,151.20846840000002)&departAfter=1516926420&arriveBefore=0&modes[]=pt_ltd_SCHOOLBUS&wp=(1,1,1,1)&es=true&tt=0&unit=auto&v=11&locale=en&ir=1&ws=1&cs=1

**Comment by JulietaMarcos** [comment]
Apparently we decided to stop adding that field for v=11 or greater. I do get it with v=10.
Also note that for scheduled segments, the `cost` field is part of a `ticket` field.

So, this isn't a bug? @jayenashar @nighthawk

**Comment by bjlange** [comment]
It's still in the documentation... if you're removing it as a feature (which is a bummer) at least update that please. And the `ticket` field is also gone in v=11; there's no structured field which has segment-level cost anymore, it's only accessible in the notes field. I just find it strange that I can get the overall monetary cost for a trip but can't break down the tickets that make up that cost in v=11.

**Comment by jayenashar** [comment]
i guess it's by design, so it's technically not a bug.  not sure what @nighthawk will decide, but i would vote to bring back the `ticket` field and document `SegmentTemplate.cost` as removed in `v=11`

**Comment by nighthawk** [comment]
Makes sense that API users would want the cost as a numeric value outside of the `notes` field. I think bringing it back for any kind of segments, not just public transport tickets, would be best.

Let's start with just having `cost` again that's just the local cost of the segment.

If deemed useful, we can additionally also add a `costComponents` list which breaks down the cost in a structured way. For public transport that could then have a single element with the ticket name and the ticket cost. For driving it could have a multiple elements for fuel, toll, and the additional wear & tear that we include. (Nice side benefit of it being self-documenting where the JSON then directly answers the questions of "what's included in your driving cost?")

**Comment by nighthawk** [comment]
@JulietaMarcos , when you fix is deployed, please add a PR to this repo explaining the new field.

What we've done it a little bit differently than what we said before to account for cases where we don't know a specific cost put instead a range (e.g., taxi, Uber, Lyft), and we'll also provide the level of accuracy of the price. This will be available in a new `localCost` field.

**Comment by nighthawk** [comment]
@bjlange, take a look at https://github.com/skedgo/tripgo-api/pull/79/files#diff-cee5f7d8431cdc0efefd4cd810aac19cR2115 for what'll be coming through shortly.

**Comment by bjlange** [comment]
Looks great, thanks for adding this! When can we expect it to be in production?

**Comment by MarianoTucat** [comment]
The plan is to have this in production today, will let you know when that is confirmed.

**Comment by MarianoTucat** [comment]
confirmed they are in production now @bjlange
