### ISSUE TITLE
tt = preferred or min or max?

### ISSUE THREAD

**Issue by jayenashar** [skedgo/tripgo-api#82]
```
tt
integer >= 0
default: 3

Preferred transfer time in minutes.
```

should that say minimum?

**Comment by nighthawk** [comment]
As far as I know: Theoretically it's "preferred" as we do allow changes with less than that time but they get punished with a huge hassle cost, which means that practically it's a "minimum". The edge case where you do get trips in practice with transfer times less than that is where it's the last departure of the day and waiting till the next morning has an even high hassle cost. @JulietaMarcos, please confirm.

**Comment by JulietaMarcos** [comment]
It's an actual minimum. We don't explore transfer times lower than that. I think the only reason why we may get a slightly shorter transfer is because of pwit inaccuracies (after enhancing the transfer time may get shortened a bit).

**Comment by jayenashar** [comment]
Shall we update the documentation to say "preferred minimum" so people don't think it's a "preferred limit"?  In this way, it is future-proof in case we update it to work as Adrian described.

**Comment by nighthawk** [comment]
Good idea!

**Comment by JulietaMarcos** [comment]
Sounds good to me, too. Done here: #83.

**Comment by jayenashar** [comment]
closing for now.  subscribe to #83 if you are interested in this issue.
