### ISSUE TITLE
Add option to always allow taking bicycles on public transport

### ISSUE THREAD

**Issue by nighthawk** [skedgo/tripgo-api#84]
The main use case for this are foldable bicycles.

This would be implemented as a new boolean toggle that can be sent to routing and which would then be used with the `cy_bic` mode.

Note that this input should not apply to bike-share networks. For those it should depend on information available about that bike share network itself (or its bikes), rather than this input to the routing engine.

**Comment by jdani156** [comment]
Indicating that the user with be taking the bike with them through the entire trip would be perfect. That's my exact use case.

**Comment by nighthawk** [comment]
We're looking into this at the moment. Heads-up: In addition to the adjustment to the routing engine to take bicycles on any public transport, it'll also require an adjustment to allow pushing/carrying a bicycle along footpaths (otherwise you could not get to public transport with your bicycle, even if it's a folding one). Those parts of a cycling leg will get marked with `dismount=true` in the JSON output.

**Comment by ludoviclaffineur** [comment]
👍

**Comment by nighthawk** [comment]
A `fb=true` input parameter to routing will be available in the coming days. Looking forward to feedback!

**Comment by nighthawk** [comment]
This has since been deployed to production.
