### ISSUE TITLE
Routing not returning car results for trips starting on a particular location in SF

### ISSUE THREAD

**Issue by MarianoTucat** [skedgo/tripgo-api#88]
Sample query:

`https://api.tripgo.com/v1/routing.json?from=(37.8054678,-122.4064022)&to=(37.442390,-122.159560)&v=11&locale=en&wp=(1,1,1,1)&departAfter=1529164800&modes[]=me_car`

Location obtained after geocoding "55 Francisco Street, San Francisco, CA" using Google Places.

**Comment by jdani156** [comment]
The FROM parameter was obtained using Google Places to geocode an address. Snapping the GPS coordinate to the road will return a route. But this workaround could leave out some walking information if I were to use the coordinate for public transportation, biking, or other multi modal trips

**Comment by jayenashar** [comment]
It's supposed to snap based on the modes.  So if you did walking only, then the snapping should consider pedestrian-only walkways.

**Comment by nighthawk** [comment]
Internal tracker link: https://redmine.buzzhives.com/issues/8697

**Comment by nighthawk** [comment]
@MarianoTucat, @jdani156, this is fixed. The above query now works.
