### ISSUE TITLE
Wrong fare information for SamTrans buses.

### ISSUE THREAD

**Issue by MarianoTucat** [skedgo/tripgo-api#93]
Routing result returns 3.75, where correct value is 2.25.
Confirmed GTFS source contains the correct value.
Created test to reproduce issue in branch [bug/fareIssueSanFrancisco](https://github.com/skedgo/skedgo-java/tree/bug/fareIssueSanFrancisco)
 
[TripGo web app](https://tripgo.com/@/37.4640839,-122.25257,12z#tripgo/%7B%22from%22:%7B%22co%22:%2237.48906,-122.23307%22,%20%22src%22:%22SKEDGO%22%7D,%20%22to%22:%7B%22co%22:%2237.43934,-122.26337%22,%20%22src%22:%22SKEDGO%22%7D,%20%22time%22:1524527220000,%20%22tp%22:%22LEAVE_ASAP%22,%20%22tid%22:%22-1%22,%20%22wp%22:%22(1.00,1.00,1.00,1.00)%22,%20%22tt%22:0,%20%22unit%22:%22automatic%22,%20%22ws%22:1,%20%22cs%22:1%7D///routing-%7B%22view%22:%22DETAILS%22,%20%22tripURL%22:%22https://stars.buzzhives.com/satapp/trip/89f7b839-1f8e-4011-a174-1d197aba9371%22%7D)

**Comment by fersagui** [comment]
Tested with new deploy and it is fixed now
