### ISSUE TITLE
CarPods are not in the documentation of locoations.json

### ISSUE THREAD

**Issue by thuutin** [skedgo/tripgo-api#97]
https://developer.tripgo.com/specs/#tag/Locations%2Fpaths%2F~1locations.json%2Fpost
@MarianoTucat Do we have it somewhere else?

**Comment by jayenashar** [comment]
@MarianoTucat is this deprecated?

```
"vehicles": [
                            {
                                "fuelType": "PETROL",
                                "licensePlate": "CN66RW",
                                "name": "GoGet"
                            },
                            {
                                "fuelType": "PETROL",
                                "licensePlate": "CM53ZY",
                                "name": "GoGet"
                            }
                        ]
```

Or can we use it in the app/design?

Also, should `name` be the name of the vehicle and not the operator?

**Comment by nighthawk** [comment]
Should not be deprecated and, yes, should be vehicle name, not operator's name.

**Comment by MarianoTucat** [comment]
this is fixed, doc added, car names only deployed in beta servers, not yet production ones.
